### ISSUE TITLE
Need to support VirtualBox backend

### ISSUE THREAD

**Issue by bmbouter** [SELinuxGame/selinuxgame.org#12]
This is the default for Vagrant and if the boxes were published with VirtualBox players could get started much easier without having to install an additional provider backends.

**Comment by ghost** [comment]
Works for me with Fedora 27

**Comment by bmbouter** [comment]
Recently virtualbox support was added by @dkliban so I'm closing this issue. Thanks for the confirmation @wagner-certat !
